import 'package:firebase_database/firebase_database.dart';
import 'package:firetrip/models/location_model.dart';

/// [tripId] Unique ID for every trip autogenerated by Firebase
/// [source] Source Location of the trip
/// [destination] Destination Location of the trip
/// [pickup] Date and time of pickup
/// [dropoff] Date and time of dropoff
/// [distance] Distance between source and destination locations
/// [duration] Difference between pickup and dropoff timing in "<hours>h <minutes>m" format
/// [rideRating] User rating for the trip

class TripModel {
  String? tripId;
  LocationModel? source, destination;
  DateTime? pickup, dropoff;
  num? distance;
  String? duration;
  num? rideRating;

  TripModel(
      {this.tripId,
      required this.source,
      required this.destination,
      required this.distance,
      required this.duration,
      required this.pickup,
      required this.dropoff,
      required this.rideRating});

  /// Takes a Snapshot fetched from Firebase
  /// Converts it to a TripModel object
  TripModel.fromSnapshot(DataSnapshot snap) {
    tripId = snap.key;
    source = LocationModel.fromSnapshot((snap.value as dynamic)["source"]);
    destination =
        LocationModel.fromSnapshot((snap.value as dynamic)["destination"]);
    distance = (snap.value as dynamic)["distance"];
    duration = (snap.value as dynamic)["duration"];
    pickup = DateTime.parse((snap.value as dynamic)["pickup"]);
    dropoff = DateTime.parse((snap.value as dynamic)["dropoff"]);
    rideRating = (snap.value as dynamic)["rideRating"];
  }

  /// Converts the current object to a Map which can be encoded into JSON
  /// Used for adding a trip to Firebase
  Map<String, dynamic> toJson() {
    var trip = {
      "source": source?.toJson(),
      "destination": destination?.toJson(),
      "distance": distance,
      "duration": duration,
      "pickup": pickup?.toIso8601String(),
      "dropoff": dropoff?.toIso8601String(),
      "rideRating": rideRating,
    };
    return trip;
  }
}
