import 'package:firebase_database/firebase_database.dart';

/// [id] Current User ID generated by Firebase
/// [name] Name of current user
/// [email] Email of current user
/// [phone] Phone no. of current user
/// [address] Address of current user

class UserModel {
  String? id;
  String? name;
  String? email;
  String? phone;
  String? address;

  UserModel({this.id, this.name, this.email, this.phone, this.address});

  /// Takes a DataSnapShot from Firebase and creates the [UserModel] object for it
  UserModel.fromSnapshot(DataSnapshot snap) {
    id = snap.key;
    name = (snap.value as dynamic)['name'];
    phone = (snap.value as dynamic)['phone'];
    email = (snap.value as dynamic)['email'];
    address = (snap.value as dynamic)['address'];
  }
}
